-- Customer orders
Select 
c.customernumber,
c.customername,
o.ordernumber,
od.productcode,
p.productname
From customers c
Left Join orders o
on c.customernumber = o.customernumber
Join orderdetails od
on o.ordernumber = od.ordernumber
Join products p
on od.productcode = p.productcode;

-- Order placed by specific customer
SELECT o.ordernumber, o.orderdate, p.productcode, od.quantityordered, od.priceeach
FROM orders o
JOIN orderdetails od ON o.ordernumber = od.ordernumber
JOIN products p ON od.productcode = p.productcode
WHERE o.customernumber = 103;

-- Customer by credit limit
SELECT
Phone,
Customername,
addressline1,
Concat(contactfirstname, ' ' , contactlastname) as contact_name,
creditlimit,
'High' AS limit_weightage
FROM customers
WHERE creditlimit > 110000

UNION

SELECT
Phone,
Customername,
addressline1,
Concat(contactfirstname, ' ' , contactlastname) as contact_name,
creditlimit,
'Medium' AS limit_weightage
FROM customers
WHERE creditlimit BETWEEN 40000 AND 110000

UNION

SELECT
Phone,
Customername,
addressline1,
Concat(contactfirstname, ' ' , contactlastname) as contact_name,
creditlimit,
'Low' AS limit_weightage
FROM customers
WHERE creditlimit < 40000
ORDER BY creditlimit DESC;

-- Empoyees and Managers
Select
e.employeenumber,
e.Jobtitle,
Concat(e.lastname, ' ', e.firstname) AS full_name,
Concat(em.lastname, ' ', em.firstname)AS manager,
o.phone,
o.city AS branch
FROM employees e
LEFT JOIN Employees em
ON e.reportsto = em.employeenumber
LEFT JOIN Offices o
ON o.officecode = e.officecode;

-- Inventory Turnover
SELECT p.productname, (SUM(od.quantityordered) / COUNT(DISTINCT o.orderdate)) AS inventory_turnover_ratio
FROM products p
JOIN orderdetails od ON p.productcode = od.productcode
JOIN orders o ON od.ordernumber = o.ordernumber
GROUP BY p.productcode
ORDER BY inventory_turnover_ratio DESC
LIMIT 10;

-- Top 10 customers with the most orders
SELECT c.customername, COUNT(o.ordernumber) AS total_orders
FROM customers c
JOIN orders o ON c.customernumber = o.customernumber
GROUP BY c.customernumber
ORDER BY total_orders DESC
LIMIT 10;

-- Top 10 products sold by quantity
SELECT p.productname, SUM(od.quantityordered) AS total_quantity_sold
FROM products p
JOIN orderdetails od ON p.productcode = od.productcode
GROUP BY p.productcode
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- Top 15 products with the highest profit margins
SELECT Distinct p.productname, (od.priceeach - p.buyprice) / od.priceeach AS profit_margin
FROM products p
JOIN orderdetails od ON p.productcode = od.productcode
ORDER BY profit_margin DESC
LIMIT 15;

-- Total revenue by country
SELECT c.country, SUM(od.quantityordered * od.priceeach) AS total_revenue
FROM customers c
JOIN orders o ON c.customernumber= o.customernumber
JOIN orderdetails od ON o.ordernumber = od.ordernumber
GROUP BY c.country;

-- Total revenue generated by each customer
SELECT c.customername, SUM(od.quantityordered * od.priceeach) AS total_revenue
FROM customers c
JOIN orders o ON c.customernumber = o.customernumber
JOIN orderdetails od ON o.ordernumber = od.ordernumber
GROUP BY c.customernumber;

-- Total revenue generated by each product
SELECT p.productname, SUM(od.quantityordered * od.priceeach) AS total_revenue
FROM products p
JOIN orderdetails od ON p.productcode = od.productcode
GROUP BY p.productcode;